base: /
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: Userprofile
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: userprofile
